# Generated by Django 3.2.4 on 2021-06-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('due', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
    ]
