# Generated by Django 3.2.4 on 2021-06-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210630_1349'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='clients',
        ),
    ]
