# Generated by Django 3.2.4 on 2021-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_clients_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phn', models.CharField(max_length=11, unique=True)),
                ('adress', models.CharField(max_length=200)),
                ('due', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
