# Generated by Django 4.0.5 on 2022-06-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=150, unique=True)),
                ('litter', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('pr_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sl_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('supplier_invoice_id', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
